### ISSUE TITLE
BacktraceThread hogs cpu on desktop java application

### ISSUE THREAD

**Issue by clippka** [backtrace-labs/backtrace-java#4]
While testing backtrace for my desktop application on mac, I noticed that my app had a huge cpu load while doing nothing. Taking a spindump revealed the issue

I see the BacktraceThread.run endlessly invoking Backtrace.handleBacktraceMessage:
https://github.com/backtrace-labs/backtrace-java/blob/master/src/main/java/backtrace/io/BacktraceThread.java#L55
@Override
public void run() {
    while (running) {
        backtrace.handleBacktraceMessage();
    }
    this.closing.countDown();
    LOGGER.info("BacktraceThread has completed the run method");
}
If there is nothing in the queue, Backtrace.handleBacktraceMessage simply returns immediately:
https://github.com/backtrace-labs/backtrace-java/blob/master/src/main/java/backtrace/io/Backtrace.java#L38
void handleBacktraceMessage() {
    try {
        if (queue.isEmpty()) {
            return;
        }
...

**Comment by konraddysput** [comment]
Thanks very much for this @clippka  ! The team is reviewing. @BartoszLitwiniuk Can you provide more insights?

**Comment by konraddysput** [comment]
Hey @clippka - I just wanted to get you more info about our progress. We're working on improvements for the queue mechanism that should remove the problem with high CPU usage. We will keep you posted about our progress!

**Comment by BartoszLitwiniuk** [comment]
Hey, I've created PR which fixing this issue, we still need some time to review it and test changes. I checked that this fix should decrease significantly CPU usage. We are currently working on that so this fix will be released as soon as possible. Thanks for finding and reporting this issue.

**Comment by BartoszLitwiniuk** [comment]
Hey, I'm closing this issue because we've fixed that in latest version. Thanks again for reporting this bug to us.
